apiVersion: v2
name: media-cron
description: Pluggable media file organizer, sanitizer, and cleaner Kubernetes chart
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - media
  - cleaner
  - cron
  - torrent
home: https://github.com/pirish/media-cron
sources:
  - https://github.com/pirish/media-cron
